/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.loja.view;

import br.com.loja.entities.Produto;
import br.com.loja.regras.RegrasProduto;
import javax.swing.JOptionPane;

/**
 *
 * @author dipirona
 */
public class TelaCadastro extends javax.swing.JFrame {

    TelaInicial inicial;
    private Produto produto;
    private RegrasProduto regra;
    
    /**
     * Creates new form TelaCadastro
     * @param telaInicial
     */
    
    // Dois contrutores com assinaturas diferentes
    
    // Esse é chamado quando ocorrer o evento "Adcionar"
    public TelaCadastro(TelaInicial telaInicial) {
        initComponents();
        this.inicial = telaInicial;
        this.produto = new Produto();
        this.regra = new RegrasProduto();
    }
    
    // Esse é chamado quando ocorrer o evento "Editar"
    public TelaCadastro(TelaInicial telaInicial, Produto selecionado){
        initComponents();
        this.inicial = telaInicial;
        this.regra = new RegrasProduto();
        this.produto = selecionado;
        // A janela iniciará com os campo já preenchidos
        this.txtReferencia.setText(selecionado.getReferencia());
        this.txtNomeForn.setText(selecionado.getNomeFornecedor());
        this.spnQuantidade.setValue(selecionado.getQuantidade());
        this.spnValorPago.setValue(selecionado.getValorPago());
        this.spnValorVenda.setValue(selecionado.getValorVenda());
    }
    
    // Verifica se os campos Referência e Nome do fornecedor não estão vazios
    public boolean verificar(){
        if(this.txtReferencia.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo Referência deve ser preenchido", "Aviso", JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(this.txtNomeForn.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo Nome do fornecedor deve ser preenchido", "Aviso", JOptionPane.ERROR_MESSAGE);
            return false;
        }else{
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblReferencia = new javax.swing.JLabel();
        lblNomeForn = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        lblValorPago = new javax.swing.JLabel();
        lblValorVenda = new javax.swing.JLabel();
        txtReferencia = new javax.swing.JTextField();
        txtNomeForn = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        spnQuantidade = new javax.swing.JSpinner();
        spnValorPago = new javax.swing.JSpinner();
        spnValorVenda = new javax.swing.JSpinner();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(400, 190));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        lblReferencia.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        lblReferencia.setText("Referência");

        lblNomeForn.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        lblNomeForn.setText("Nome do fornecedor");

        lblQuantidade.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        lblQuantidade.setText("Quantidade");

        lblValorPago.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        lblValorPago.setText("Valor Pago por Uni.");

        lblValorVenda.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        lblValorVenda.setText("Valor para venda");

        txtReferencia.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        txtNomeForn.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        btnSalvar.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        spnQuantidade.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));

        spnValorPago.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(200000.0f), Float.valueOf(0.5f)));

        spnValorVenda.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(200000.0f), Float.valueOf(0.5f)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblQuantidade))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeForn, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeForn)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblReferencia)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblValorVenda, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValorPago, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnQuantidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnValorVenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnValorPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReferencia)
                .addGap(2, 2, 2)
                .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNomeForn)
                .addGap(4, 4, 4)
                .addComponent(txtNomeForn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spnQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblValorPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblValorVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        // Verifica se os campos estão OK
        if(this.verificar()){
            
            this.produto.setReferencia(this.txtReferencia.getText());
            this.produto.setNomeFornecedor(this.txtNomeForn.getText());
            this.produto.setQuantidade(Integer.parseInt(this.spnQuantidade.getValue().toString()));
            this.produto.setValorPago(Float.parseFloat(this.spnValorPago.getValue().toString()));
            this.produto.setValorVenda(Float.parseFloat(this.spnValorVenda.getValue().toString()));
            
            if(this.regra.jaExiste(produto)){
                this.regra.atualizar(produto);
            }else{
                this.regra.salvar(produto);
            }

            this.dispose();// Fecha a janela cadastro
            inicial.atualizar();// Atualiza a lista da tela inicial
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNomeForn;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblReferencia;
    private javax.swing.JLabel lblValorPago;
    private javax.swing.JLabel lblValorVenda;
    private javax.swing.JSpinner spnQuantidade;
    private javax.swing.JSpinner spnValorPago;
    private javax.swing.JSpinner spnValorVenda;
    private javax.swing.JTextField txtNomeForn;
    private javax.swing.JTextField txtReferencia;
    // End of variables declaration//GEN-END:variables
}
